### ISSUE TITLE
Create basic repository layout.

### ISSUE THREAD

**Issue by KirillDogadin-std** [sidestream-tech/solhint-plugin-makerdao#1]
### Goal

Have the repository preapared for plugin rules development & testing. Have several PoC rules to kick-start the process.

### Context

https://github.com/sidestream-tech/sideblock/issues/13 introduces the set of rules and requirements. Now it's time to create the barebone plugin repository and implement several linting rules as PoC.

### Assets

https://github.com/sidestream-tech/sideblock/issues/13

### Tasks

- [ ] Add basic plugin layout:
  - [ ] `solhint-plugin-` prefixed naming
  - [ ] export array of rules as classes that implement the rule checks
- [ ] Add jest testing
