### ISSUE TITLE
Publish plugin on npm

### ISSUE THREAD

**Issue by KirillDogadin-std** [sidestream-tech/solhint-plugin-makerdao#4]
### Goal

Have the package publicly available and installable by npm

### Context

After the plugin has been developed, we need to provide the public access for it.

### Tasks

- [ ] login via cli tool https://docs.npmjs.com/cli/v9/commands/npm-login
  - [ ] depending on the location of the configuration file on you machine, add `.npmrc` to gitignore (globally)
- [ ] Rename the package to contain organisation name in front of it.
  - [ ] `@sidestream/solhint-plugin-makerdao` in `package.json`
- [ ] merge the pr with renaming (in pr use _contributes_ instead of _closes_ so that this issue remains open)
- [ ] follow the steps [here](https://docs.npmjs.com/creating-and-publishing-an-organization-scoped-package)
  - [ ] run `npm publish --access public` in the package directory.
